=== sebastianBoehringer/CodeGenerator/src/main/resources/SDMetricsConfig/metamodel.dtd
<!ELEMENT sdmetricsmetamodel ( modelelement+ ) >
        <!ATTLIST sdmetricsmetamodel
                version CDATA #REQUIRED>

        <!ELEMENT modelelement (#PCDATA|attribute)*>
        <!ATTLIST modelelement
                name CDATA #REQUIRED
                parent CDATA "sdmetricsbase">

        <!ELEMENT attribute (#PCDATA)>
        <!ATTLIST attribute
                name CDATA #REQUIRED
                type (ref|extref|data) "data"
                multiplicity (one|many) "one">

=== sebastianBoehringer/CodeGenerator/src/main/resources/SDMetricsConfig/metamodel2.xml
<?xml version="1.0"?>
<!DOCTYPE sdmetricsmetamodel SYSTEM 'metamodel.dtd'>

<!-- metamodel.xml

SDMetrics V2.3 default metamodel definition file for UML2.x
Copyright (c) 2002-2018 Juergen Wuest

The MIT License

Permission is hereby granted, free of charge, to any person obtaining a copy
of this SDMetrics project file (the "Project File"), to deal in the Project File 
without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Project File, and to permit persons to whom the Project File is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Project File.

THE PROJECT FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE PROJECT FILE.

Note: this license grant only applies to this Project File, and not to any
other part of SDMetrics.

-->

<sdmetricsmetamodel version="2.0">


    <modelelement name="sdmetricsbase">
        <attribute name="context" type="ref">Owner of the element in the UML model.</attribute>
        <attribute name="id">Unique identifier of the model element.</attribute>
        <attribute name="name">Name of the element in UML model.</attribute>
        <attribute name="comments" type="ref" multiplicity="many">The comments for the model element.</attribute>
    </modelelement>

    <!-- classes, interfaces, attributes, operations -->
    <modelelement name="class">
        <attribute name="visibility">Visibility of the element (public, protected, package, private).</attribute>
        <attribute name="abstract">Boolean indicating if the element is abstract.</attribute>
        <attribute name="leaf">Boolean indicating if the element can have specializations.</attribute>
        <attribute name="ownedattributes" type="ref" multiplicity="many">The attributes of the element.</attribute>
        <attribute name="ownedoperations" type="ref" multiplicity="many">The operations of the element.</attribute>
        <attribute name="nestedclassifiers" type="ref" multiplicity="many">The nested classifiers of the element.
        </attribute>
        <attribute name="generalizations" type="ref" multiplicity="many">The generalizations owned by the element.
        </attribute>
        <attribute name="interfacerealizations" type="ref" multiplicity="many">The interface realizations owned by the
            element.
        </attribute>
        <attribute name="connectors" type="ref" multiplicity="many">The connectors owned by the element.</attribute>
    </modelelement>
    <modelelement name="interface">
        <attribute name="ownedattributes" type="ref" multiplicity="many">The attributes of the interface.</attribute>
        <attribute name="ownedoperations" type="ref" multiplicity="many">The operations of the interface.</attribute>
        <attribute name="nestedclassifiers" type="ref" multiplicity="many">The nested classifiers of the interface.
        </attribute>
        <attribute name="generalizations" type="ref" multiplicity="many">The generalizations owned by the interface.
        </attribute>
    </modelelement>

    <modelelement name="datatype">
        <attribute name="ownedattributes" type="ref" multiplicity="many">The attributes of the element.</attribute>
        <attribute name="ownedoperations" type="ref" multiplicity="many">The operations of the element.</attribute>
        <attribute name="generalizations" type="ref" multiplicity="many">The generalizations owned by the element.
        </attribute>
    </modelelement>
    <modelelement name="enumeration" parent="datatype">
        <attribute name="ownedliterals" type="ref" multiplicity="many">The literals of the enumeration.</attribute>
    </modelelement>
    <modelelement name="enumerationliteral"/>
    <modelelement name="primitivetype" parent="datatype"/>

    <modelelement name="connector">
        <attribute name="ends" type="ref" multiplicity="many">The connector ends of the connector.</attribute>
    </modelelement>
    <modelelement name="connectorend">
        <attribute name="role" type="ref">The element that is attached at this connector end.</attribute>
    </modelelement>

    <modelelement name="property">
        <attribute name="visibility">Visibility of the feature (public, private, protected, package).</attribute>
        <attribute name="propertytype" type="ref">Reference to the feature type (class, data type etc).</attribute>
        <attribute name="isreadonly">Changeability of the feature. Values: true, false (default if not specified).
        </attribute>
        <attribute name="association" type="ref">Reference to association if this is an association end.</attribute>
        <attribute name="aggregation">The aggregation kind of the property: shared, composite, or none (default).
        </attribute>
        <attribute name="qualifiers" type="ref" multiplicity="many">The qualifier attributes of the property.
        </attribute>
    </modelelement>

    <modelelement name="port" parent="property"/>

    <modelelement name="operation">
        <attribute name="visibility">Visibility of the operation (public, private, protected, package).</attribute>
        <attribute name="abstract">Boolean indicating if operation is abstract.</attribute>
        <attribute name="isquery">Boolean indicating if operation is a query that does not change the classifier's
            state.
        </attribute>
        <attribute name="ownedparameters" type="ref" multiplicity="many">The parameters of the operation.</attribute>
    </modelelement>
    <modelelement name="parameter">
        <attribute name="kind">The direction of the parameter: in (default), out, inout, return.</attribute>
        <attribute name="parametertype" type="ref">Reference to the parameter type (class, data type etc).</attribute>
    </modelelement>
    <modelelement name="method"/>

    <!-- models, packages -->

    <modelelement name="package">
        <attribute name="ownedmembers" type="ref" multiplicity="many">The owned member elements.</attribute>
    </modelelement>
    <modelelement name="model" parent="package"/>

    <!-- relationships: association, generalization, ... -->
    <modelelement name="association">
        <attribute name="memberends" type="ref" multiplicity="many">The member ends of the association.</attribute>
        <attribute name="ownedends" type="ref" multiplicity="many">The owned ends of the association (not navigable
            association ends).
        </attribute>
        <attribute name="generalizations" type="ref" multiplicity="many">The generalizations owned by the association.
        </attribute>
    </modelelement>

    <modelelement name="associationclass" parent="association"/>

    <modelelement name="generalization">
        <attribute name="general" type="ref">Link to the parent in the generalization.</attribute>
    </modelelement>

    <modelelement name="interfacerealization">
        <attribute name="contract" type="ref">Link to the realized interface.</attribute>
    </modelelement>

    <modelelement name="dependency">
        <attribute name="supplier" type="ref" multiplicity="many">Links to the supplier elements of the relationship.
        </attribute>
        <attribute name="client" type="ref" multiplicity="many">Links to the client elements of the relationship.
        </attribute>
    </modelelement>

    <modelelement name="abstraction" parent="dependency"/>
    <modelelement name="realization" parent="abstraction"/>
    <modelelement name="substitution" parent="realization"/>
    <modelelement name="usage" parent="dependency"/>


    <!-- instance specifications, connectors. -->

    <modelelement name="collaboration" parent="class">
        <attribute name="ownedbehaviors" type="ref" multiplicity="many">Behavior specifications owned by the
            collaboration.
        </attribute>
    </modelelement>

    <modelelement name="interaction" parent="class">
        <attribute name="lifelines" type="ref" multiplicity="many">The lifelines involved in the interaction.
        </attribute>
        <attribute name="messages" type="ref" multiplicity="many">The messages sent within the interaction.</attribute>
        <attribute name="fragments" type="ref" multiplicity="many">The message occurrence specifications and combined
            fragments of the interaction.
        </attribute>
    </modelelement>

    <modelelement name="instancespecification">
        <attribute name="classifier" type="ref" multiplicity="many">Links to the classifiers that this entity is an
            instance of.
        </attribute>
        <attribute name="deployments" type="ref" multiplicity="many">The deployments where this instance specification
            is the target.
        </attribute>
    </modelelement>

    <modelelement name="lifeline">
        <attribute name="represents" type="ref">The interaction participant that this lifeline represents.</attribute>
    </modelelement>

    <modelelement name="message">
        <attribute name="receiveevent" type="ref">Occurrence specification for the message reception.</attribute>
        <attribute name="sendevent" type="ref">Occurrence specification for the message sending.</attribute>
        <attribute name="sort">The sort of communication (synchCall, asynchCall, asynchSignal, etc.).</attribute>
    </modelelement>

    <modelelement name="occurrencespec">
